architecture: VildDetpro
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams

MaskRCNN:
  backbone: ResNet
  neck: FPN
  rpn_head: RPNHead
#  bbox_head: BBoxHead
#  mask_head: MaskHead
  roi_head: StandardRoiHead

ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: sync_bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4

FPN:
  out_channel: 256
  norm_type: sync_bn

RPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    anchor_sizes: [[32], [64], [128], [256], [512]]
    strides: [4, 8, 16, 32, 64]
  rpn_target_assign:
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.7
    use_random: True
  train_proposal:
    min_size: 0.001
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 1000
    topk_after_collect: True
  test_proposal:
    min_size: 0.001
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

StandardRoiHead:
  bbox_head: Shared4Conv1FCBBoxHead
  bbox_roi_extractor:
    resolution: 7
    sampling_ratio: 0
    aligned: True
  mask_head: FCNMaskHead
  mask_roi_extractor:
    resolution: 14
    sampling_ratio: 0
    aligned: True
  load_feature: False
  bbox_assigner: MaxIoUAssignerDetPro
  bbox_sampler: RandomSamplerDetPro
  train_mask_size: 28
  train_pos_weight: -1

Shared4Conv1FCBBoxHead:
  in_channels: 256
  fc_out_channels: 1024
  roi_feat_size: 7
  num_classes: 1203
  reg_class_agnostic: True
  ensemble: True
  with_cls: False

FCNMaskHead:
  num_convs: 4
  in_channels: 256
  conv_out_channels: 256
  class_agnostic: True
  num_classes: 1203

MaxIoUAssignerDetPro:
  pos_iou_thr: 0.5
  neg_iou_thr: 0.5
  min_pos_iou: 0.5
  match_low_quality: True
  ignore_iof_thr: -1

RandomSamplerDetPro:
  num: 512
  pos_fraction: 0.25
  neg_pos_ub: -1
  add_gt_as_proposals: True











